# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('post_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('topic', models.SmallIntegerField(null=True)),
                ('topic_2', models.SmallIntegerField(null=True)),
                ('created', models.BigIntegerField(db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('topic_rating', models.CharField(max_length=200)),
            ],
        ),
    ]
