# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='choice1',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='choice2',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postId',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='title',
        ),
    ]
