# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='postdb',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
