# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickme', '0002_auto_20170601_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('post_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('topic', models.SmallIntegerField(null=True)),
                ('topic_2', models.SmallIntegerField(null=True)),
                ('created', models.BigIntegerField(db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('topic_rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
