# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickme', '0003_auto_20170605_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=200)),
            ],
        ),
    ]
